#!/usr/bin/php 
<?php
/*
 Copyright (c) 2009 Ben Lumley (@benlumley)

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
*/

/**
 * Added _config include
 * Used tabs instead of spaces
 *
 * @author Martijn van Beek
 * @since 28 Juni 2011
 *
 */

require(dirname(__FILE__).'/config.php');

foreach ($files as $key=>$file) {
	foreach ($includes as $include) {
		if (strpos($file, $include)) {
			continue 2;
		}
	}
	foreach ($excludes as $exclude) {
		if (preg_match($exclude, $file)) {
			unset($files[$key]);
			continue 2;
		}
	}
}

if (isset($argv[1]) && $argv[1]=='config') {
	$draw = "AREA";
	foreach ($files as $file) {
		$sitename = sitename($file);
		echo hashname($file) . "_access.label $sitename\n";
		echo hashname($file) . "_access.draw $draw\n";
		$draw = "STACK";
	}
	echo "graph_category apache\n";
	echo "graph_title Apache Accesses By Vhost\n";
	echo "graph_vlabel Requests per sec\n";
	echo "graph_info This graph shows requests per second by virtual host\n";
} else {
	foreach ($files as $file) {
		$access_rate = calculate_rate($file, $access_lines);
		echo hashname($file) . "_access.value " . $access_rate . "\n";
	}
}

function calculate_rate($file, $num_lines) {
	$ago = get_time($file, $num_lines);
	$increment = floor($num_lines/2);
	$its = 0;
	$opp = false;
	while ($ago < 270 || $ago > 330) {
		if ($ago < 270) {
			if ($opp == "sub") {
				$increment = floor($increment/2);
			}
			$num_lines = $num_lines + $increment;
			$opp = "add";
		} elseif ($ago > 330) {
			if ($opp == "add") {
				$increment = floor($increment/2);
			}
			$num_lines = max(1, $num_lines - $increment);
			$opp = "sub";
		}
		$ago = get_time($file, $num_lines);
		if ($num_lines == 1 && $ago > 330) {
			return 0.000;
		}
		$its++;
		if ($its == 10) {
			break;
		}
	}
	
	if ( $num_lines > 0 && $ago > 0 ) {
		return round($num_lines/$ago, 4);
	}else{
		return 0;
	}
}
